# build and deploy streamlit app using GitHub actions and requirements.txt to Netlify
name: Streamlit App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
      python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    deploy:
      name: Deploy
        steps:
          - uses: streamlit/github-actions@master
            with:
            token: ${{ secrets.GITHUB_TOKEN }}
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            app-name: my-app
            requirements-file: requirements.txt