name: Streamlit App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Prepare Environment
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip
          sudo pip3 install awsebcli
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build and tag Docker image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: streamlit-demo:latest
      
      - name: Deploy to Elastic Beanstalk environment
        id: create-environment
        run: |
          
          eb init efi-smirnov-streamlit-demo-env --platform Docker --region eu-west-2
          eb use efi-smirnov-streamlit-demo-env
          eb deploy
 
        
